# -*- coding: utf-8 -*-
"""cashier.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1inqkqrRezd-mGpAcbPMQlerdOoXL3jOx
"""

import pandas as pd # untuk membuat dataframe
import sys # untuk mengakhiri program

class Transaction:

    def __init__(self):
        self.list_item = []
        self.list_jumlah_item = []
        self.list_harga_item = []
        self.list_harga_total = []
        self.df = None

    def basket(self):
        """Function untuk menambahkan item ke keranjang belanja.
        Sebelum input nama, jumlah dan harga item, user akan ditanya jumlah jenis
        item yang akan dibayar. Setelah semua item sudah diinput, maka
        akan keluar output dataframe nama, jumlah, harga/item dan total harga dari
        semua item.
        """

        try:
            print("\033[1m" + "===============Selamat Datang di Super Indo===============" + "\033[0m")
            jumlah_jenis_items = int(input("Berapa jenis item yang anda akan bayar? "))

        except ValueError:
            raise ValueError("Masukkan dalam bentuk angka")

        for i in range(jumlah_jenis_items):
            item = str(input("\nMasukkan nama item yang akan dibeli: "))
            try:
                jumlah_item = int(input("Masukkan jumlah item: "))
                harga_item = int(input("Masukkan harga item: "))
            except ValueError:
                raise ValueError("Masukkan dalam bentuk angka")
            harga_total = jumlah_item * harga_item
            self.list_item.append(item)
            self.list_jumlah_item.append(jumlah_item)
            self.list_harga_item.append(harga_item)
            self.list_harga_total.append(harga_total)

        # convert list to dictionary
        dict_items = {
            'Item': self.list_item,
            'Jumlah item': self.list_jumlah_item,
            'Harga/item': self.list_harga_item,
            'Harga total': self.list_harga_total
        }

        # convert dictionary to datafame
        self.df = pd.DataFrame(dict_items)
        # assign index dataframe agar dimulai dari 1
        self.df.index = self.df.index + 1
        # set index name
        self.df.index.name = "No."
        print("\nBerikut adalah item yang anda akan beli")
        print(self.df)
        print("")

    def update_items(self):
        """Function untuk mengedit item yang ada di keranjang belanja.
        User dibeli 4 pilihan edit. Untuk mengedit item, user harus
        menginput nomor urut item sesuai dengan yang tertera pada tabel
        item di keranjang belanja
        """
        
        print("\033[1m" + "===================Update Item Belanja====================" + "\033[0m")
        print("Berikut adalah item yang berada di keranjang belanja anda:")
        print(self.df)
        print("----------------------------------------------------------")

        update_item = input("Apakah ada item belanja anda yang ingin diganti (yes/no)? ")

        if update_item == "yes":
            print(
                "Tulis 'yes' pada salah satu pilihan berikut jika anda ingin mengganti/menambah item di keranjang anda")
            print("")
            ask1 = str(input("Ingin menambah item (yes/no): "))
            ask2 = str(input("Hanya nama item saja (yes/no): "))
            ask3 = str(input("Hanya jumlah itemnya saja (yes/no): "))
            ask4 = str(input("Hanya harga item saja (yes/no): "))

            if ask1 == "yes":
                print("------------------------------------------")
                jumlah_update_item = int(input("Berapa jenis item yang ingin ditambah? "))
                for i in range(jumlah_update_item):
                    item = str(input("\nMasukkan nama item yang akan dibeli: "))
                    try:
                        jumlah_item = int(input("Masukkan jumlah item: "))
                        harga_item = int(input("Masukkan harga item: "))
                    except ValueError:
                        raise ValueError("Masukkan dalam bentuk angka")
                    harga_total = jumlah_item * harga_item
                    self.list_item.append(item)
                    self.list_jumlah_item.append(jumlah_item)
                    self.list_harga_item.append(harga_item)
                    self.list_harga_total.append(harga_total)

                dict_items = {
                    'Item': self.list_item,
                    'Jumlah item': self.list_jumlah_item,
                    'Harga/item': self.list_harga_item,
                    'Harga total': self.list_harga_total
                    }
                self.df = pd.DataFrame(dict_items)
                self.df.index = self.df.index + 1
                self.df.index.name = "No."
                print("\nBerikut adalah item yang anda akan beli")
                print(self.df)
                print("")

            elif ask2 == "yes":
                print("------------------------------------------")
                jumlah_update_item = int(input("Berapa jenis barang yang ingin anda ganti? "))
                for i in range(jumlah_update_item):
                    try:
                        index_item_lama = int(input("\nMasukkan no. urut item yang akan diganti: "))
                        index = index_item_lama - 1
                        update_item_name = str(input("Masukkan nama item baru: "))
                        self.list_item[index] = update_item_name
                    except IndexError:
                        raise IndexError("No urut item tidak ada dalam keranjang anda")

                dict_items = {
                    'Item': self.list_item,
                    'Jumlah item': self.list_jumlah_item,
                    'Harga/item': self.list_harga_item,
                    'Harga total': self.list_harga_total
                    }
                self.df = pd.DataFrame(dict_items)
                self.df.index = self.df.index + 1
                self.df.index.name = "No."
                print("\nBerikut adalah item yang anda akan beli")
                print(self.df)
                print("")

            elif ask3 == "yes":
                print("------------------------------------------")
                jumlah_update_item = int(input("Berapa jenis barang yang ingin anda ganti? "))
                for i in range(jumlah_update_item):
                    try:
                        index_item_lama = int(input("\nMasukkan no. urut item yang akan diganti: "))
                        index = index_item_lama - 1
                        update_item_qty = int(input("Masukkan jumlah item baru: "))
                        update_item_price = self.list_harga_item[index]
                        update_total_price = update_item_qty * update_item_price
                        self.list_jumlah_item[index] = update_item_qty
                        self.list_harga_total[index] = update_total_price
                    except IndexError:
                        raise IndexError("No urut item tidak ada dalam keranjang anda")

                dict_items = {
                    'Item': self.list_item,
                    'Jumlah item': self.list_jumlah_item,
                    'Harga/item': self.list_harga_item,
                    'Harga total': self.list_harga_total
                    }
                self.df = pd.DataFrame(dict_items)
                self.df.index = self.df.index + 1
                self.df.index.name = "No."
                print("\nBerikut adalah item yang anda akan beli")
                print(self.df)
                print("")

            elif ask4 == "yes":
                print("------------------------------------------")
                jumlah_update_item = int(input("Berapa jenis barang yang ingin anda ganti? "))
                for i in range(jumlah_update_item):
                    try:
                        index_item_lama = int(input("\nMasukkan no. urut item yang akan diganti: "))
                        index = index_item_lama - 1
                        update_item_price = int(input("Masukkan harga item: "))
                        update_item_qty = self.list_jumlah_item[index]
                        update_total_price = update_item_qty * update_item_price
                        self.list_jumlah_item[index] = update_item_qty
                        self.list_harga_total[index] = update_total_price
                    except IndexError:
                        raise IndexError("No urut item tidak ada dalam keranjang anda")

                dict_items = {
                    'Item': self.list_item,
                    'Jumlah item': self.list_jumlah_item,
                    'Harga/item': self.list_harga_item,
                    'Harga total': self.list_harga_total
                    }
                self.df = pd.DataFrame(dict_items)
                self.df.index = self.df.index + 1
                self.df.index.name = "No."
                print("\nBerikut adalah item yang anda akan beli")
                print(self.df)
                print("")

        elif update_item == "no":
            pass

        else:
            raise NameError("Tulis 'yes' untuk mengganti item atau 'no' jika tidak")

    def delete_items(self):
        """Function untuk menghapus item yang ada di keranjang belanja.
        User dibeli 2 pilihan delete (delete semua item/reset dan delete beberapa
        item). Untuk menghapus item, user harus menginput nomor urut item yang ingin
        dihapus sesuai dengan yang tertera pada tabel item di keranjang belanja
        """
        dict_items = {
                    'Item': self.list_item,
                    'Jumlah item': self.list_jumlah_item,
                    'Harga/item': self.list_harga_item,
                    'Harga total': self.list_harga_total
                    }
        self.df = pd.DataFrame(dict_items)
        self.df.index = self.df.index + 1
        self.df.index.name = "No."

        jumlah_item = len(self.list_item)
        print("\033[1m" + "===================Hapus Item Belanja=====================" + "\033[0m")
        print("Berikut adalah item yang anda akan beli")
        print(self.df)

        print("----------------------------------------------------------")
        delete_item = str(input("Apakah ada item belanja anda yang ingin hapus (yes/no)? "))

        if delete_item == "yes":
            delete_all = str(input("\nApakah anda ingin menghapus semua item (yes/no)? "))
            if delete_all == "no":
                delete_jumlah_item = int(input("Berapa jumlah item yang akan dihapus? "))

                if delete_jumlah_item >= 1:
                    for i in range(delete_jumlah_item):
                        try:
                            no_index = int(input("Masukkan no. urut item yang ingin dihapus: "))
                            delete_index = (no_index - 1) - (jumlah_item - len(self.list_item))
                            self.list_item.pop(delete_index)
                            self.list_jumlah_item.pop(delete_index)
                            self.list_harga_item.pop(delete_index)
                            self.list_harga_total.pop(delete_index)
                        except ValueError:
                            raise ValueError("No urut item tidak ada dalam keranjang anda")

                    dict_items = {
                    'Item': self.list_item,
                    'Jumlah item': self.list_jumlah_item,
                    'Harga/item': self.list_harga_item,
                    'Harga total': self.list_harga_total
                    }
                    self.df = pd.DataFrame(dict_items)
                    self.df.index = self.df.index + 1
                    self.df.index.name = "No."
                    print("\nBerikut adalah list item di keranjang anda")
                    print(self.df)
                    print("")

            elif delete_all == "yes":
                self.list_item.clear()
                self.list_jumlah_item.clear()
                self.list_harga_item.clear()
                self.list_harga_total.clear()
                print("Semua item berhasil dihapus \n")
                sys.exit("Silahkan masukkan kembali item belanja anda")

            else:
                raise NameError("Tulis 'yes' untuk menghapus item atau 'no' jika tidak")

        elif delete_item == "no":
            pass

        else:
            raise NameError("Tulis 'yes' untuk mengganti item atau 'no' jika tidak")

    def check_order(self):
        """Function untuk mengecek item apa saja yang ada di keranjang belanja user
        """
        dict_items = {
                    'Item': self.list_item,
                    'Jumlah item': self.list_jumlah_item,
                    'Harga/item': self.list_harga_item,
                    'Harga total': self.list_harga_total
                    }
        self.df = pd.DataFrame(dict_items)
        self.df.index = self.df.index + 1
        self.df.index.name = "No."
        
        print("\033[1m" + "=================Cek Item Belanjaan Anda==================" + "\033[0m")
        check = str(input("Apakah anda ingin melihat item di keranjang anda (yes/no)? "))
        if check == "yes":
          if len(self.list_item) > 0:
            print("Berikut adalah item yang anda akan beli")
            print(self.df)
            print("")
          else:
            sys.exit("Silahkan masukkan kembali item belanja anda")
        elif check == "no":
          pass
        else:
          raise NameError("Tulis 'yes' untuk mengecek item atau 'no' jika tidak")

    def total_price(self):
        """Function untuk menampilkan total belanja yang harus dibayarkan user.
        Nominal diskon yang didapatkan user berdasarkan total belanja. User juga
        dapat mengetahui jumlah diskon yang mereka dapatkan
        """
        dict_items = {
                    'Item': self.list_item,
                    'Jumlah item': self.list_jumlah_item,
                    'Harga/item': self.list_harga_item,
                    'Harga total': self.list_harga_total
                    }
        self.df = pd.DataFrame(dict_items)
        self.df.index = self.df.index + 1
        self.df.index.name = "No."

        if len(self.list_item) > 0:
          print("\033[1m" +"===========Terima kasih telah berbelanja disini===========" +"\033[0m")
          total_harga = sum(self.list_harga_total)
          if total_harga > 500000:
            total_harga = total_harga - (total_harga * 0.1)
            print("Item yang dibeli")
            print(self.df)
            print(f"Selamat anda mendapat diskon 10% \nTotal Belanja yang harus dibayarkan adalah Rp. {total_harga}")
          elif total_harga > 300000:
            total_harga = total_harga - (total_harga * 0.08)
            print("Item yang dibeli")
            print(self.df)
            print(f"Selamat anda mendapat diskon 8% \nTotal Belanja yang harus dibayarkan adalah Rp. {total_harga}")
          elif total_harga > 200000:
            total_harga = total_harga - (total_harga * 0.05)
            print("Item yang dibeli")
            print(self.df)
            print(f"Selamat anda mendapat diskon 5% \nTotal Belanja yang harus dibayarkan adalah Rp. {total_harga}")
          else:
            print("Item yang dibeli")
            print(self.df)
            print(f"Total Belanja yang harus dibayarkan adalah Rp. {total_harga}")

        else:
            sys.exit("Silahkan masukkan kembali item belanja anda")

# Running class dan semua function
cashier = Transaction()
cashier.basket()
cashier.update_items()
cashier.delete_items()
cashier.check_order()
cashier.total_price()

